const TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR";
const CREATE_PLAYER = "CREATE_PLAYER";
const SUBMIT_PLAYER_NUMBERS = "SUBMIT_PLAYER_NUMBERS";
const SUBMIT_TEST_NUMBERS = "SUBMIT_TEST_NUMBERS";
const RESET_TEST = "RESET_TEST";
const CHANGE_VIEW_MODE = "CHANGE_VIEW_MODE";
const CHECK_WINNING_TICKETS = "CHECK_WINNING_TICKETS";
const CALCULATE_WINNING_AMOUNT = "CALCULATE_WINNING_AMOUNT";
const GET_PLAYER_MONEY = "GET_PLAYER_MONEY";
const GET_OPERATOR_MONEY = "GET_OPERATOR_MONEY";
const SET_NUMBERS_ARRAY = "SET_NUMBERS_ARRAY";
const SUBMIT_WINNING_NUMBERS = "SUBMIT_WINNING_NUMBERS";
const SUBSTRACT_OPERATOR_MONEY = "SUBSTRACT_OPERATOR_MONEY";
const UPDATE_SUMMARY = "UPDATE_SUMMARY";
const RESET_STATE = "RESET_STATE";
const RESET_APP = "RESET_APP";

export {
  TOGGLE_SIDEBAR,
  CREATE_PLAYER,
  SUBMIT_PLAYER_NUMBERS,
  SUBMIT_TEST_NUMBERS,
  RESET_TEST,
  CHANGE_VIEW_MODE,
  CHECK_WINNING_TICKETS,
  CALCULATE_WINNING_AMOUNT,
  GET_PLAYER_MONEY,
  GET_OPERATOR_MONEY,
  SET_NUMBERS_ARRAY,
  SUBMIT_WINNING_NUMBERS,
  SUBSTRACT_OPERATOR_MONEY,
  UPDATE_SUMMARY,
  RESET_STATE,
  RESET_APP,
};
